apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
      - name: bookings
        image: yourdockerhub/bookings-service
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/bookings_db
---
apiVersion: v1
kind: Service
metadata:
  name: bookings
spec:
  type: NodePort
  selector:
    app: bookings
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30009
